import type { LanguageStat } from "./types";

export const EXT_TO_LANG: Readonly<Record<string, string>> = {
  ts: "TypeScript",
  tsx: "TypeScript",
  js: "JavaScript",
  jsx: "JavaScript",
  mjs: "JavaScript",
  rs: "Rust",
  py: "Python",
  pyi: "Python",
  go: "Go",
  lua: "Lua",
  java: "Java",
  cpp: "C++",
  cc: "C++",
  cxx: "C++",
  c: "C",
  h: "C/C++ Header",
  hpp: "C++ Header",
  rb: "Ruby",
  php: "PHP",
  swift: "Swift",
  kt: "Kotlin",
  kts: "Kotlin",
  scala: "Scala",
  sh: "Shell",
  bash: "Shell",
  zsh: "Shell",
  html: "HTML",
  css: "CSS",
  scss: "SCSS",
  sass: "SCSS",
  json: "JSON",
  yaml: "YAML",
  yml: "YAML",
  toml: "TOML",
  md: "Markdown",
  mdx: "Markdown",
  sql: "SQL",
  r: "R",
  jl: "Julia",
  zig: "Zig",
  nim: "Nim",
  dart: "Dart",
  ex: "Elixir",
  exs: "Elixir",
  vue: "Vue",
  svelte: "Svelte",
  astro: "Astro",
  cs: "C#",
  fs: "F#",
  hs: "Haskell",
  ml: "OCaml",
  v: "V",
  tf: "HCL",
  dockerfile: "Dockerfile",
} as const;

export const LANG_COLORS: Readonly<Record<string, string>> = {
  TypeScript: "#3178c6",
  JavaScript: "#f7df1e",
  Rust: "#ff8c42",
  Python: "#ffd166",
  Go: "#00d4ff",
  Lua: "#00e68a",
  Java: "#ed8b00",
  "C++": "#f34b7d",
  C: "#555555",
  "C/C++ Header": "#555555",
  "C++ Header": "#f34b7d",
  Ruby: "#cc342d",
  PHP: "#777bb4",
  Swift: "#f05138",
  Kotlin: "#a97bff",
  Scala: "#dc322f",
  Shell: "#89e051",
  HTML: "#e34c26",
  CSS: "#563d7c",
  SCSS: "#c6538c",
  JSON: "#7a8a9e",
  YAML: "#cb171e",
  TOML: "#9c4221",
  Markdown: "#e6edf3",
  SQL: "#e38c00",
  R: "#198ce7",
  Julia: "#9558b2",
  Zig: "#ec915c",
  Nim: "#ffe953",
  Dart: "#00b4ab",
  Elixir: "#6e4a7e",
  Vue: "#41b883",
  Svelte: "#ff3e00",
  Astro: "#ff5d01",
  "C#": "#68217a",
  "F#": "#378bba",
  Haskell: "#5e5086",
  OCaml: "#3be133",
  V: "#4f87c5",
  HCL: "#844fba",
  Dockerfile: "#384d54",
} as const;

export const HEATMAP_COLORS = [
  "#0f1923",
  "#0a3d2a",
  "#007a4d",
  "#00b36b",
  "#00e68a",
  "#33ffaa",
] as const;

export const HEATMAP_THRESHOLDS = [0, 1, 50, 200, 500, 1000] as const;

export const SKIP_DIRS: ReadonlySet<string> = new Set([
  "node_modules",
  ".git",
  "dist",
  "build",
  "out",
  ".next",
  "__pycache__",
  ".venv",
  "venv",
  "target",
  "vendor",
  ".cache",
  "coverage",
  ".tox",
  ".mypy_cache",
  ".pytest_cache",
  ".turbo",
  ".parcel-cache",
  "bower_components",
  ".gradle",
  ".idea",
  ".vscode",
  ".vs",
  ".DS_Store",
  ".svn",
  ".hg",
  "Pods",
  ".cargo",
  ".rustup",
]);

export const MAX_FILE_SIZE = 1024 * 1024;

export const SESSION_GAP_MS = 2 * 60 * 60 * 100;

export const COMMIT_TYPES_DEFS: ReadonlyArray<{
  type: string;
  label: string;
  color: string;
}> = [
  { type: "feat", label: "Fitur Baru", color: "#00e68a" },
  { type: "fix", label: "Bug Fix", color: "#ff5c5c" },
  { type: "refactor", label: "Refaktor", color: "#00d4ff" },
  { type: "docs", label: "Dokumentasi", color: "#ffd166" },
  { type: "perf", label: "Performa", color: "#ff8c42" },
  { type: "test", label: "Testing", color: "#ff6b9d" },
  { type: "chore", label: "Maintenance", color: "#7a8a9e" },
  { type: "style", label: "Styling", color: "#c6538c" },
  { type: "ci", label: "CI/CD", color: "#555555" },
  { type: "build", label: "Build", color: "#4a5568" },
] as const;

